### ISSUE TITLE
Warning: circular argument reference - tree

### ISSUE THREAD

**Issue by artur79** [trailblazer/trailblazer-activity#27]
It started to appear since version *0.8.0*, I think the problem is that in arguments we have:
 ```tree: tree```

https://github.com/trailblazer/trailblazer-activity/blob/master/lib/trailblazer/activity/present.rb#L22

when it should be just: 
```tree:```

**Comment by apotonick** [comment]
@seuros While you're at it, can you fix that? Thanks @artur79 <3

**Comment by artur79** [comment]
yes of course, I will prepare PR

**Comment by seuros** [comment]
Fixed in master.
