### ISSUE TITLE
Graph#outputs

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-activity#41]
Would it be more consistent to have `Graph(MyActivity).outputs` instead of `MyActivity.to_h[:outputs]`?

**Comment by yogeshjain999** [comment]
But we would need to initialize `Graph` object and I'm thinking if it would incur any additional cost, like generating intermediate structures in future.

**Comment by apotonick** [comment]
Completely right, an `Activity` has a `Schema`, and the schema per definition keeps all outputs, so we don't need `Graph` here.
