### ISSUE TITLE
Cannot move from fail step to pass step

### ISSUE THREAD

**Issue by wafcio** [trailblazer/trailblazer-activity#8]
```
step :find_by_auth
pass :assign_email, pass_fast: true
fail :find_by_email, Output(:success) => :assign_authentication
pass :assign_authentication, pass_fast: true
fail :create
```

I use it for user authentication by omniauth. When user isn’t found by authentication then it moves to find_by_email and then I see error message:

```
Trailblazer::Circuit::IllegalOutputSignalError: [#<Trailblazer::Activity::TaskBuilder::Task user_proc=find_by_email>][ Trailblazer::Activity::Right ]
```

I have tried replace `Output(:sucess)` with `Output(Trailblazer::Activity::Right, :success)` but error still appears.

**Comment by apotonick** [comment]
Hi @wafcio, thanks! Is that in an `Activity` or an `Operation`? If the former, what strategy (`Railway` or `Path`)?

**Comment by wafcio** [comment]
I used it inside Operation.

**Comment by wafcio** [comment]
I wrote simple:

```
class MyOperation < Trailblazer::Operation
  step :find_by_auth
  pass :assign_email, pass_fast: true
  fail :find_by_email, Output(:success) => :assign_authentication
  pass :assign_authentication, pass_fast: true
  fail :create

  ...
end
```

So I don't know which startegy it uses.

**Comment by apotonick** [comment]
This should work:

```ruby
step :find_by_auth
pass :assign_email, pass_fast: true
fail :find_by_email, Output(:success) => "assign_authentication"
pass :assign_authentication, pass_fast: true, id: "assign_authentication"
fail :create
```

**Comment by wafcio** [comment]
Thanks it works, I think it will be good to keep the same convention with having symbols, instead of one time write step name as symbol and another time as string.

**Comment by apotonick** [comment]
Thanks @wafcio for your example, documented here: http://trailblazer.to/api-docs/#activity-output-id

**Comment by opti** [comment]
@apotonick does it mean that `fail :upload_to_azure,  Output(:success) => :success` is not working anymore?

**Comment by apotonick** [comment]
Yepp! You like it?

**Comment by opti** [comment]
Seems to be less confusing :)

**Comment by opti** [comment]
@apotonick although I find another thing confusing

```ruby
Output(:success) => "End.success"
```
Why not `End(:success)`?

**Comment by apotonick** [comment]
Currently, `End( ... )` will always create a new end instead of finding the existing. Existing tasks you always reference by ID (string), but, yeah, I've thought about that as well. Anyway, this could be added later since it's backward-compatible.

**Comment by opti** [comment]
Thanks for clarifying.

**Comment by apotonick** [comment]
And thanks for commenting on the new API, please keep coming your suggestions! :metal:
